import type { Lead, Project, CaseItem, ClientItem } from '@/lib/db';

export type DbSchema = {
  leads: Lead[];
  projects: Project[];
  cases: CaseItem[];
  clients: ClientItem[];
};

export const INITIAL_DATA: DbSchema = {
  leads: [
    {
      id: 'lead-1',
      name: 'Автоателье APEX — Руслан',
      contact: '+7 (928) 444-55-66 / @apex_detailing',
      message: 'Нужен премиальный сайт детейлинг-центра с калькулятором оклейки и рендером.',
      budget: '45 000 ₽',
      niche: 'Авто',
      notes: 'Новая заявка через форму сайта Valence.',
      status: 'new',
      createdAt: '2026-08-14T10:00:00.000Z',
    },
    {
      id: 'lead-2',
      name: 'Отель Николь — Тариэл',
      contact: '+7 (918) 123-45-67 / @nikol_hotel',
      message: 'Разработка официального сайта гостевого комплекса с бронированием номеров.',
      budget: '60 000 ₽',
      niche: 'Отели',
      notes: 'Созвонились, обсудили структуру и дизайн-систему.',
      status: 'contacted',
      createdAt: '2026-08-13T10:00:00.000Z',
    },
    {
      id: 'lead-3',
      name: 'Стоматология Prime — Игорь',
      contact: 'info@prime-clinic.ru / +7 (861) 900-11-22',
      message: 'Онлайн запись пациентов и личный кабинет для сети клиник.',
      budget: '90 000 ₽',
      niche: 'Медицина',
      notes: 'Отправили коммерческое предложение, ждем подписания договора.',
      status: 'kp_sent',
      createdAt: '2026-08-12T10:00:00.000Z',
    },
    {
      id: 'lead-4',
      name: 'MestiDelivery — Каха',
      contact: '+995 599 11-22-33 / @mesti_admin',
      message: 'PWA сервис доставки еды по всей Грузии.',
      budget: '50 000 ₽',
      niche: 'E-Commerce',
      notes: 'Получена предоплата 50%, заходим в стадию Next.js кода.',
      status: 'prepaid',
      createdAt: '2026-08-10T10:00:00.000Z',
    },
    {
      id: 'lead-5',
      name: 'Ретро Драйв — ЗАЗ 965',
      contact: '@zaz_retro / +7 (999) 777-88-99',
      message: 'Сервис онлайн бронирования ретро автомобилей.',
      budget: '40 000 ₽',
      niche: 'Авто',
      notes: 'Сайт в процессе верстки и тестирования.',
      status: 'in_progress',
      createdAt: '2026-08-07T10:00:00.000Z',
    },
    {
      id: 'lead-6',
      name: 'Black Coffee Co.',
      contact: 'contact@blackcoffee.store',
      message: 'Сайт онлайн заказов и меню для сети кофеен.',
      budget: '35 000 ₽',
      niche: 'E-Commerce',
      notes: 'Проект сдан, финальная оплата поступила.',
      status: 'done',
      createdAt: '2026-08-02T10:00:00.000Z',
    },
  ],
  projects: [
    {
      id: 'proj-1',
      title: 'Детейлинг APEX — Промо Сайт',
      clientName: 'Руслан (APEX)',
      progress: 35,
      status: 'design',
      paidAmount: 22500,
      remainingAmount: 22500,
      deadline: '2026-08-25',
      createdAt: '2026-08-11T10:00:00.000Z',
    },
    {
      id: 'proj-2',
      title: 'Гостевой Комплекс Николь',
      clientName: 'Тариэл (Отель Николь)',
      progress: 65,
      status: 'code',
      paidAmount: 30000,
      remainingAmount: 30000,
      deadline: '2026-08-28',
      createdAt: '2026-08-06T10:00:00.000Z',
    },
    {
      id: 'proj-3',
      title: 'MestiDelivery Georgia PWA',
      clientName: 'Mesti Group',
      progress: 88,
      status: 'testing',
      paidAmount: 25000,
      remainingAmount: 25000,
      deadline: '2026-08-20',
      createdAt: '2026-07-30T10:00:00.000Z',
    },
    {
      id: 'proj-4',
      title: 'Prime Clinic — Система Записи',
      clientName: 'Игорь (Prime)',
      progress: 100,
      status: 'delivered',
      paidAmount: 90000,
      remainingAmount: 0,
      deadline: '2026-08-18',
      createdAt: '2026-07-20T10:00:00.000Z',
    },
  ],
  cases: [
    {
      id: '01',
      title: 'RETRO ZAZ',
      tag: 'сайт · онлайн-бронирование',
      year: '2026',
      result: 'прокат ретро-авто ЗАЗ-965',
      url: 'https://zazretro.web.app/',
      image: '/cases/retro-zaz-desktop.png',
      createdAt: '2026-07-15T10:00:00.000Z',
    },
    {
      id: '02',
      title: 'MestiDelivery',
      tag: 'PWA · сервис доставки еды',
      year: '2026',
      result: 'быстрая доставка в Грузии',
      url: 'https://mestidelivery.com/',
      image: '/cases/mesti-desktop.png',
      createdAt: '2026-07-30T10:00:00.000Z',
    },
    {
      id: 'case-villa-palma',
      title: 'Villa Palma Suite 4★',
      tag: 'бутик-отель · сочи / адлер',
      year: '2026',
      result: 'официальный сайт 4★',
      url: 'https://palmasochihotel.web.app/',
      createdAt: '2026-08-16T10:00:00.000Z',
    },
  ],
  clients: [
    {
      id: 'client-1',
      name: 'Руслан APEX',
      company: 'Детейлинг APEX',
      phone: '+7 (928) 444-55-66',
      telegram: '@apex_detailing',
      niche: 'Авто',
      ordersCount: 2,
      totalSpent: 85000,
      lastOrderDate: '2026-08-10',
      notes: 'Постоянный клиент. Планирует заказать интеграцию телеграм-бота.',
    },
    {
      id: 'client-2',
      name: 'Тариэл',
      company: 'Гостевой Комплекс Николь',
      phone: '+7 (918) 123-45-67',
      telegram: '@nikol_hotel',
      niche: 'Отели',
      ordersCount: 1,
      totalSpent: 60000,
      lastOrderDate: '2026-08-05',
      notes: 'Заказан модуль бронирования и интеграция с календарем.',
    },
    {
      id: 'client-3',
      name: 'Георгий Кахидзе',
      company: 'MestiDelivery Georgia',
      phone: '+995 599 12-34-56',
      telegram: '@george_mesti',
      niche: 'E-Commerce',
      ordersCount: 3,
      totalSpent: 220000,
      lastOrderDate: '2026-07-28',
      notes: 'Заказывали PWA сайт + приложение доставки.',
    },
    {
      id: 'client-4',
      name: 'Игорь Васильев',
      company: 'Стоматология Prime',
      phone: '+7 (861) 900-11-22',
      telegram: '@prime_clinic',
      niche: 'Медицина',
      ordersCount: 2,
      totalSpent: 180000,
      lastOrderDate: '2026-06-15',
      notes: 'Заказывал сайт и систему записи пациентов.',
    },
  ],
};
